

During handling of the above exception, another exception occurred:

WARNING Post data for post with pk=12
WARNING Post data for post with pk=12
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/blog/120/
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/export-to-csv/
INFO /home/upay/PycharmProjects/POC_project_v2/auths/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /admin.
WARNING Not Found: /admin/auths/export-to-csv/
WARNING Not Found: /favicon.ico
WARNING Not Found: /admin/export-to-csv/
WARNING Not Found: /favicon.ico
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /blog/export-to-csv
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/blog/upload-csv/
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/blog/upload-csv/
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/blog/import-csv/
WARNING Not Found: /blog/export-to-csv
WARNING Not Found: /blog/export-to-csv
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /blog/export-to-csv
WARNING Not Found: /favicon.ico
WARNING Not Found: /blog/export-to-csv
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /blog/export-to-csv
WARNING Not Found: /favicon.ico
INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blog_comments/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /favicon.ico
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/register/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 264, in connect
    sock = self.retry.call_with_retry(
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 265, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 627, in _connect
    raise err
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 615, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/auths/views.py", line 51, in post
    redis_client.set(email, otp, 36000)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/commands/core.py", line 2341, in set
    return self.execute_command("SET", *pieces, **options)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/client.py", line 533, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 1086, in get_connection
    connection.connect()
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/redis/connection.py", line 270, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
DEBUG 
def xstarmap(task, it):
    return 1

DEBUG 
def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1

DEBUG 
def accumulate(self, *args, **kwargs):
    return 1

DEBUG 
def chunks(task, it, n):
    return 1

DEBUG 
def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

DEBUG 
def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1

DEBUG 
def xmap(task, it):
    return 1

DEBUG 
def send_notification_mail(self, otp, recipient_list):
    return 1

DEBUG 
def chain(*args, **kwargs):
    return 1

DEBUG 
def backend_cleanup():
    return 1

INFO /home/upay/PycharmProjects/POC_project_v2/auths/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING Bad Request: /
ERROR Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING Bad Request: /favicon.ico
INFO /home/upay/PycharmProjects/POC_project_v2/POC_project_v2/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/POC_project_v2/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /favicon.ico
INFO /home/upay/PycharmProjects/POC_project_v2/POC_project_v2/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/blogs/views.py changed, reloading.
INFO Watching for file changes with StatReloader
