INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/check/
WARNING Not Found: /api/check/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/send/
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
WARNING Not Found: /api/send/
WARNING Not Found: /api/send/
WARNING Bad Request: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/send/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Unauthorized: /api/create/product/
WARNING Bad Request: /api/create/product/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Not Found: /api/buy/product/
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 81, in post
    if stock >= items and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 81, in post
    if stock >= items and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 84, in post
    if stock >= items and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 77, in post
    owner = product_queryset[0]['owner_id']
TypeError: tuple indices must be integers or slices, not str
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 79, in post
    stock = product_queryset[0]['stock']
TypeError: tuple indices must be integers or slices, not str
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 80, in post
    stock = product_queryset[0]['stock']
TypeError: tuple indices must be integers or slices, not str
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 80, in post
    if stock >= quantity and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/buy/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 81, in post
    if stock >= quantity and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 81, in post
    if stock >= quantity and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 80, in post
    if stock >= quantity and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
WARNING Bad Request: /api/buy/
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 80, in post
    if stock >= quantity and stock >= 0:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 87, in post
    owner_balance = Balance.objects.get(user_id=owner)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
transactions.models.Balance.DoesNotExist: Balance matching query does not exist.
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
ERROR Internal Server Error: /api/buy/
Traceback (most recent call last):
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/transactions/views.py", line 87, in post
    owner_balance = Balance.objects.get(user_id=owner)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/upay/PycharmProjects/POC_project_v2/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
transactions.models.Balance.DoesNotExist: Balance matching query does not exist.
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Using selector: EpollSelector
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/serializers.py changed, reloading.
INFO Watching for file changes with StatReloader
WARNING Unauthorized: /api/check/
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
INFO /home/upay/PycharmProjects/POC_project_v2/transactions/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
WARNING Bad Request: /api/buy/
DEBUG Starting new HTTP connection (1): localhost:8000
DEBUG http://localhost:8000 "GET /api/check/ HTTP/1.1" 200 17
WARNING Not Found: /api/send/
